### ISSUE TITLE
update with centos 6 and 7

### ISSUE THREAD

**Issue by ozbillwang** [CSCfi/ansible-role-sssd#1]
This role looks gr8, and I'd like to use for Centos 6 and 7 as well.

My understand is, it should be run directly with `when` condition adjusted.

**Comment by martbhell** [comment]
I don't understand. Please be more specific.  I use this for both 6 and 7 already.

**Comment by ozbillwang** [comment]
when run on centos 7, it bypassed all setting.

**Comment by martbhell** [comment]
Did you set this variable?

<pre>sssd_configure: True
</pre>
